// <auto-generated />
using System;
using AcmeCorporationLibrary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AcmeCorporationLibrary.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231101005501_AddSubmissionOver18String")]
    partial class AddSubmissionOver18String
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AcmeCorporationLibrary.Models.SerialNumberModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("ConsumeTimes")
                        .HasColumnType("bigint");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("SerialNumbers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConsumeTimes = 2L,
                            Guid = "f8235195-1f73-4bc4-8ac9-ad4b679041c4",
                            IsActive = true
                        },
                        new
                        {
                            Id = 2,
                            ConsumeTimes = 2L,
                            Guid = "1ff5a093-6e1d-4421-954a-a86c18c300f7",
                            IsActive = true
                        },
                        new
                        {
                            Id = 3,
                            ConsumeTimes = 2L,
                            Guid = "09a4095b-09ea-4424-b771-5aff833359ce",
                            IsActive = true
                        },
                        new
                        {
                            Id = 4,
                            ConsumeTimes = 2L,
                            Guid = "5a0b73a6-42cd-4252-a6ec-5dd6fb10430e",
                            IsActive = true
                        },
                        new
                        {
                            Id = 5,
                            ConsumeTimes = 2L,
                            Guid = "185ae65a-e0c6-4697-896c-ba9709306c99",
                            IsActive = true
                        },
                        new
                        {
                            Id = 6,
                            ConsumeTimes = 2L,
                            Guid = "64a134c5-d36e-4dd8-928b-c639d89f001c",
                            IsActive = true
                        },
                        new
                        {
                            Id = 7,
                            ConsumeTimes = 2L,
                            Guid = "36390dac-3a83-481d-afcc-a98e8d25545e",
                            IsActive = true
                        },
                        new
                        {
                            Id = 8,
                            ConsumeTimes = 2L,
                            Guid = "316dc451-04da-45e8-9169-1d34ac5b42ce",
                            IsActive = true
                        },
                        new
                        {
                            Id = 9,
                            ConsumeTimes = 2L,
                            Guid = "4a95accf-676f-4a92-ae03-2cf7132f5ba4",
                            IsActive = true
                        },
                        new
                        {
                            Id = 10,
                            ConsumeTimes = 2L,
                            Guid = "6394efc9-0683-4b00-add5-578f8d554fa4",
                            IsActive = true
                        },
                        new
                        {
                            Id = 11,
                            ConsumeTimes = 2L,
                            Guid = "b2408f99-f790-4a77-90f5-755028c7ed5a",
                            IsActive = true
                        },
                        new
                        {
                            Id = 12,
                            ConsumeTimes = 2L,
                            Guid = "63fa6930-207e-4c7d-b62c-480b8cd6755a",
                            IsActive = true
                        },
                        new
                        {
                            Id = 13,
                            ConsumeTimes = 2L,
                            Guid = "73637f22-c33e-4bc4-ad9d-1a658391075d",
                            IsActive = true
                        },
                        new
                        {
                            Id = 14,
                            ConsumeTimes = 2L,
                            Guid = "57bf3363-7389-46c2-83f0-9683b19a43f8",
                            IsActive = true
                        },
                        new
                        {
                            Id = 15,
                            ConsumeTimes = 2L,
                            Guid = "e0e2377e-313b-4130-bffe-5bc2f7185fcf",
                            IsActive = true
                        },
                        new
                        {
                            Id = 16,
                            ConsumeTimes = 2L,
                            Guid = "1776d010-0069-47e7-a484-9943b052aa51",
                            IsActive = true
                        },
                        new
                        {
                            Id = 17,
                            ConsumeTimes = 2L,
                            Guid = "23eedc0d-6bc5-4b2e-9426-5ffe876b0aec",
                            IsActive = true
                        },
                        new
                        {
                            Id = 18,
                            ConsumeTimes = 2L,
                            Guid = "604d1bab-6e9f-4ab0-b32c-389daaca292d",
                            IsActive = true
                        },
                        new
                        {
                            Id = 19,
                            ConsumeTimes = 2L,
                            Guid = "9c4822ff-4fc3-4131-82b0-941fcb0e19ef",
                            IsActive = true
                        },
                        new
                        {
                            Id = 20,
                            ConsumeTimes = 2L,
                            Guid = "a509d161-23f9-4afc-a2b7-77c2eb91312c",
                            IsActive = true
                        },
                        new
                        {
                            Id = 21,
                            ConsumeTimes = 2L,
                            Guid = "94a2fa17-5ddc-40d0-bc2d-976646ed76ff",
                            IsActive = true
                        },
                        new
                        {
                            Id = 22,
                            ConsumeTimes = 2L,
                            Guid = "258e3a71-8c98-41dd-b5f2-8307a3127ed2",
                            IsActive = true
                        },
                        new
                        {
                            Id = 23,
                            ConsumeTimes = 2L,
                            Guid = "a51a336a-6dcf-49f4-881b-3d687fad00b6",
                            IsActive = true
                        },
                        new
                        {
                            Id = 24,
                            ConsumeTimes = 2L,
                            Guid = "38947803-20be-40ae-8464-8a408f3d2487",
                            IsActive = true
                        },
                        new
                        {
                            Id = 25,
                            ConsumeTimes = 2L,
                            Guid = "56c8e63f-bed0-4556-89e1-d00509ebd2b9",
                            IsActive = true
                        },
                        new
                        {
                            Id = 26,
                            ConsumeTimes = 2L,
                            Guid = "e5964986-9399-43f8-8016-e5394f320a8e",
                            IsActive = true
                        },
                        new
                        {
                            Id = 27,
                            ConsumeTimes = 2L,
                            Guid = "a8c249c2-ff96-4b9f-8262-e3220e2e7ebc",
                            IsActive = true
                        },
                        new
                        {
                            Id = 28,
                            ConsumeTimes = 2L,
                            Guid = "fef0fdd1-b974-4970-9847-57e9adc75fec",
                            IsActive = true
                        },
                        new
                        {
                            Id = 29,
                            ConsumeTimes = 2L,
                            Guid = "40a88009-7817-4e27-b8ee-3415ae98ac28",
                            IsActive = true
                        },
                        new
                        {
                            Id = 30,
                            ConsumeTimes = 2L,
                            Guid = "dcde552b-ecb3-40f4-8ea4-c3560115cee9",
                            IsActive = true
                        },
                        new
                        {
                            Id = 31,
                            ConsumeTimes = 2L,
                            Guid = "6280995a-98c2-4bdc-a201-7f9e7cabfee8",
                            IsActive = true
                        },
                        new
                        {
                            Id = 32,
                            ConsumeTimes = 2L,
                            Guid = "0454d39c-d09f-4866-b512-057685abc72b",
                            IsActive = true
                        },
                        new
                        {
                            Id = 33,
                            ConsumeTimes = 2L,
                            Guid = "6e87777e-f21b-4b70-8fa9-6737f2d7ab6e",
                            IsActive = true
                        },
                        new
                        {
                            Id = 34,
                            ConsumeTimes = 2L,
                            Guid = "21d9dbbf-4748-43d0-991f-6a22e1015207",
                            IsActive = true
                        },
                        new
                        {
                            Id = 35,
                            ConsumeTimes = 2L,
                            Guid = "893c357e-16d6-421d-821e-fd75589bff08",
                            IsActive = true
                        },
                        new
                        {
                            Id = 36,
                            ConsumeTimes = 2L,
                            Guid = "29db9e90-161b-4bdd-8beb-8a9b7eef2f2e",
                            IsActive = true
                        },
                        new
                        {
                            Id = 37,
                            ConsumeTimes = 2L,
                            Guid = "2f3289ba-f152-4342-aa76-4745c18b47e6",
                            IsActive = true
                        },
                        new
                        {
                            Id = 38,
                            ConsumeTimes = 2L,
                            Guid = "e0e27414-7512-4c30-84f5-172e89d856c8",
                            IsActive = true
                        },
                        new
                        {
                            Id = 39,
                            ConsumeTimes = 2L,
                            Guid = "780eac06-5e0a-4e18-a03f-13c03252ff2e",
                            IsActive = true
                        },
                        new
                        {
                            Id = 40,
                            ConsumeTimes = 2L,
                            Guid = "27a06b15-437e-48ae-82e5-6d87b5c1c612",
                            IsActive = true
                        },
                        new
                        {
                            Id = 41,
                            ConsumeTimes = 2L,
                            Guid = "60a83e91-c971-4513-914c-d44855b50a63",
                            IsActive = true
                        },
                        new
                        {
                            Id = 42,
                            ConsumeTimes = 2L,
                            Guid = "c788845d-f81f-42fb-892e-c8f7e05ccd3f",
                            IsActive = true
                        },
                        new
                        {
                            Id = 43,
                            ConsumeTimes = 2L,
                            Guid = "00288e22-548e-4804-8b2e-3ab9201f4265",
                            IsActive = true
                        },
                        new
                        {
                            Id = 44,
                            ConsumeTimes = 2L,
                            Guid = "16645ed1-133f-4f93-b3e6-9a5550c7ed0e",
                            IsActive = true
                        },
                        new
                        {
                            Id = 45,
                            ConsumeTimes = 2L,
                            Guid = "18644266-b66a-4675-9454-eeaba81726ff",
                            IsActive = true
                        },
                        new
                        {
                            Id = 46,
                            ConsumeTimes = 2L,
                            Guid = "f6e81eda-42eb-4b7d-b248-3a8f6ecc9b30",
                            IsActive = true
                        },
                        new
                        {
                            Id = 47,
                            ConsumeTimes = 2L,
                            Guid = "64fbfdfb-f0da-4dbc-801d-9ff611f57bc2",
                            IsActive = true
                        },
                        new
                        {
                            Id = 48,
                            ConsumeTimes = 2L,
                            Guid = "87a46c4d-59b0-4498-9123-b824b7cef05b",
                            IsActive = true
                        },
                        new
                        {
                            Id = 49,
                            ConsumeTimes = 2L,
                            Guid = "7dccbd78-bb85-468c-a97c-ea97b24256cc",
                            IsActive = true
                        },
                        new
                        {
                            Id = 50,
                            ConsumeTimes = 2L,
                            Guid = "6df17efc-66b1-40e0-9e44-1b9ebf09a171",
                            IsActive = true
                        },
                        new
                        {
                            Id = 51,
                            ConsumeTimes = 2L,
                            Guid = "fe49855b-44ab-4ad5-95c3-68ab8a0e56a4",
                            IsActive = true
                        },
                        new
                        {
                            Id = 52,
                            ConsumeTimes = 2L,
                            Guid = "a1910ce4-a9e5-4ef2-8921-7186f7d5f92e",
                            IsActive = true
                        },
                        new
                        {
                            Id = 53,
                            ConsumeTimes = 2L,
                            Guid = "514a072d-8f0b-4e00-b634-fc203bd1899c",
                            IsActive = true
                        },
                        new
                        {
                            Id = 54,
                            ConsumeTimes = 2L,
                            Guid = "9a48ede5-b888-4168-9ca0-6f12cc7e2666",
                            IsActive = true
                        },
                        new
                        {
                            Id = 55,
                            ConsumeTimes = 2L,
                            Guid = "5bfe1bf0-7743-472d-ab9f-62c8145efdef",
                            IsActive = true
                        },
                        new
                        {
                            Id = 56,
                            ConsumeTimes = 2L,
                            Guid = "92d5291f-4e41-4550-896f-d6d11d332b52",
                            IsActive = true
                        },
                        new
                        {
                            Id = 57,
                            ConsumeTimes = 2L,
                            Guid = "e4c7a83f-57c0-4bfa-98e0-9c708d202ce9",
                            IsActive = true
                        },
                        new
                        {
                            Id = 58,
                            ConsumeTimes = 2L,
                            Guid = "589b5493-8eba-40c5-8fbe-7349400b3b51",
                            IsActive = true
                        },
                        new
                        {
                            Id = 59,
                            ConsumeTimes = 2L,
                            Guid = "17a14a78-00f1-47ef-9011-6a9bb72cf90f",
                            IsActive = true
                        },
                        new
                        {
                            Id = 60,
                            ConsumeTimes = 2L,
                            Guid = "20505bb2-23f3-48c5-a323-887d7951020c",
                            IsActive = true
                        },
                        new
                        {
                            Id = 61,
                            ConsumeTimes = 2L,
                            Guid = "ce387555-432b-4374-ba9f-4a86d1feace6",
                            IsActive = true
                        },
                        new
                        {
                            Id = 62,
                            ConsumeTimes = 2L,
                            Guid = "037f37f0-37eb-4300-8239-ed53e715f847",
                            IsActive = true
                        },
                        new
                        {
                            Id = 63,
                            ConsumeTimes = 2L,
                            Guid = "383f1f46-5bf3-4479-a25d-3b23af1b9036",
                            IsActive = true
                        },
                        new
                        {
                            Id = 64,
                            ConsumeTimes = 2L,
                            Guid = "90169bd9-57bd-4480-a770-b3fbd7b67888",
                            IsActive = true
                        },
                        new
                        {
                            Id = 65,
                            ConsumeTimes = 2L,
                            Guid = "8f9d5095-30f6-4813-b7f6-598bf6799ce8",
                            IsActive = true
                        },
                        new
                        {
                            Id = 66,
                            ConsumeTimes = 2L,
                            Guid = "5f49cf0b-1020-4e02-b7fa-12f86732bcc4",
                            IsActive = true
                        },
                        new
                        {
                            Id = 67,
                            ConsumeTimes = 2L,
                            Guid = "4693cb9b-9bff-4fd1-a51a-a46c6146cc50",
                            IsActive = true
                        },
                        new
                        {
                            Id = 68,
                            ConsumeTimes = 2L,
                            Guid = "f7b8860a-5ed6-4afe-8d2f-30c15960350a",
                            IsActive = true
                        },
                        new
                        {
                            Id = 69,
                            ConsumeTimes = 2L,
                            Guid = "47cf40f0-676b-4a6f-8719-da8834208043",
                            IsActive = true
                        },
                        new
                        {
                            Id = 70,
                            ConsumeTimes = 2L,
                            Guid = "b53438d5-4a43-4b71-a201-e9fadd138384",
                            IsActive = true
                        },
                        new
                        {
                            Id = 71,
                            ConsumeTimes = 2L,
                            Guid = "26ca4bef-aa8d-4db5-adf3-9ae6b72e71e2",
                            IsActive = true
                        },
                        new
                        {
                            Id = 72,
                            ConsumeTimes = 2L,
                            Guid = "c3905fd5-15e9-4056-96bb-4ae47edf2b40",
                            IsActive = true
                        },
                        new
                        {
                            Id = 73,
                            ConsumeTimes = 2L,
                            Guid = "48b60f5d-18af-466b-a954-bfaa14f05bff",
                            IsActive = true
                        },
                        new
                        {
                            Id = 74,
                            ConsumeTimes = 2L,
                            Guid = "9e9f9397-e65e-48d2-8e7d-f985e06f8dcf",
                            IsActive = true
                        },
                        new
                        {
                            Id = 75,
                            ConsumeTimes = 2L,
                            Guid = "c9cd0f77-0027-432d-855a-fd01f86706f4",
                            IsActive = true
                        },
                        new
                        {
                            Id = 76,
                            ConsumeTimes = 2L,
                            Guid = "b6093bd2-bbc5-4cf4-9e97-7dad863072bc",
                            IsActive = true
                        },
                        new
                        {
                            Id = 77,
                            ConsumeTimes = 2L,
                            Guid = "54cd59ec-5088-40a5-8112-83cb536b5492",
                            IsActive = true
                        },
                        new
                        {
                            Id = 78,
                            ConsumeTimes = 2L,
                            Guid = "0bff9568-074a-41a9-bcee-f8d5a465fa7a",
                            IsActive = true
                        },
                        new
                        {
                            Id = 79,
                            ConsumeTimes = 2L,
                            Guid = "848af053-b485-4cea-8ece-b828391c1a40",
                            IsActive = true
                        },
                        new
                        {
                            Id = 80,
                            ConsumeTimes = 2L,
                            Guid = "25f05495-e519-40b1-be2d-ff01cc19472a",
                            IsActive = true
                        },
                        new
                        {
                            Id = 81,
                            ConsumeTimes = 2L,
                            Guid = "2570568e-0805-46d7-9263-8110a92140a1",
                            IsActive = true
                        },
                        new
                        {
                            Id = 82,
                            ConsumeTimes = 2L,
                            Guid = "c3ef4d0d-dbf5-4275-93d1-5c930524058b",
                            IsActive = true
                        },
                        new
                        {
                            Id = 83,
                            ConsumeTimes = 2L,
                            Guid = "82b7b3cf-d97d-4102-9e09-9ce9654993e8",
                            IsActive = true
                        },
                        new
                        {
                            Id = 84,
                            ConsumeTimes = 2L,
                            Guid = "6fbed212-8ee1-450a-bba2-0851dc3b0eed",
                            IsActive = true
                        },
                        new
                        {
                            Id = 85,
                            ConsumeTimes = 2L,
                            Guid = "aa3063ce-bf19-4c2d-8fe6-7bb1ccbd24c4",
                            IsActive = true
                        },
                        new
                        {
                            Id = 86,
                            ConsumeTimes = 2L,
                            Guid = "1d3cf1e0-8695-452c-b62b-2438dd4416aa",
                            IsActive = true
                        },
                        new
                        {
                            Id = 87,
                            ConsumeTimes = 2L,
                            Guid = "890ef138-6be0-4213-a31d-8aa7ea5f6fb9",
                            IsActive = true
                        },
                        new
                        {
                            Id = 88,
                            ConsumeTimes = 2L,
                            Guid = "0aa5107a-6251-467e-aeff-6b2603bebff8",
                            IsActive = true
                        },
                        new
                        {
                            Id = 89,
                            ConsumeTimes = 2L,
                            Guid = "4e907d77-cfb0-4280-9c72-77a59f9b4f35",
                            IsActive = true
                        },
                        new
                        {
                            Id = 90,
                            ConsumeTimes = 2L,
                            Guid = "0df49356-ed71-4e77-b0d1-f317dbcec62f",
                            IsActive = true
                        },
                        new
                        {
                            Id = 91,
                            ConsumeTimes = 2L,
                            Guid = "402cf86d-9462-4385-b63e-5efcfdb5ae32",
                            IsActive = true
                        },
                        new
                        {
                            Id = 92,
                            ConsumeTimes = 2L,
                            Guid = "8a76ac15-1a3d-495a-a9dc-98034ac5dc84",
                            IsActive = true
                        },
                        new
                        {
                            Id = 93,
                            ConsumeTimes = 2L,
                            Guid = "56461c23-0cbc-4740-965d-001b7e7419b1",
                            IsActive = true
                        },
                        new
                        {
                            Id = 94,
                            ConsumeTimes = 2L,
                            Guid = "251ec7c5-0538-4dbb-b4c6-25949898af22",
                            IsActive = true
                        },
                        new
                        {
                            Id = 95,
                            ConsumeTimes = 2L,
                            Guid = "b4bf29d1-e79e-468d-8aab-4172e06b5782",
                            IsActive = true
                        },
                        new
                        {
                            Id = 96,
                            ConsumeTimes = 2L,
                            Guid = "807c585e-4d2a-4011-a93d-53e6ac468cfe",
                            IsActive = true
                        },
                        new
                        {
                            Id = 97,
                            ConsumeTimes = 2L,
                            Guid = "c581c845-85eb-49eb-ad59-7e8f8ce72f0f",
                            IsActive = true
                        },
                        new
                        {
                            Id = 98,
                            ConsumeTimes = 2L,
                            Guid = "25aa361f-563a-434c-b103-7c1969abab7c",
                            IsActive = true
                        },
                        new
                        {
                            Id = 99,
                            ConsumeTimes = 2L,
                            Guid = "ec4671a0-824b-45fb-b28f-06d8312a1750",
                            IsActive = true
                        },
                        new
                        {
                            Id = 100,
                            ConsumeTimes = 2L,
                            Guid = "a8ae828d-82de-417d-a228-bce8bc66bef5",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("AcmeCorporationLibrary.Models.SubmissionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsOver18")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductSerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Submission");
                });
#pragma warning restore 612, 618
        }
    }
}
